### ISSUE TITLE
Migrar o tutorial de Git & GitHub

### ISSUE THREAD

**Issue by johnidm** [OESTIDigital/OESTIDigital.github.io#1]
https://github.com/OESTIDigital/tutoriais/blob/master/git-github.md

**Comment by felippepuhle** [comment]
Vamos colocar os mesmos textos dos tutoriais no blog?

**Comment by johnidm** [comment]
@lippep acredito que sim

**Comment by ferreira2006** [comment]
O que acham de criar uma postagem no oestidigital.github.io para depois vamos adicionando os links dos projetos que forem aparecendo?

**Comment by johnidm** [comment]
@ferreira2006 seguindo o que conversamos no Yoututbe acho interessante isso também.

Podemos escrecer um post no blog e ir colocando esses links, podemos usar umas temáticas para escrever sobre isso, por exemplo:
- A importancia de participar de projetos open source.
- Como posso compartilhar meu código fonte.
- Dicas para compartilhar código
- etc

Isso pode ser interessante, o que acha?

**Comment by ferreira2006** [comment]
É válido.

**Comment by felippepuhle** [comment]
Achei bacana! o template do blog vamos dar uma customizada também?

**Comment by johnidm** [comment]
Exato, estou negociando um terceiro post sobre o repostório `code-kata`
