### ISSUE TITLE
Texto para colocar no Sobre do blog

### ISSUE THREAD

**Issue by johnidm** [OESTIDigital/OESTIDigital.github.io#3]
Retirado do grupo do Face - OESTI Digital - Programadores do extremo oeste - SC

```
Reunir programadores com interesse em compartilhar informação 
e técnicas de forma livre na área.
```

Retirado da página do Face - OESTI Digital 

```
Comunidade e grupo de usuários dos profissionais de TI do oeste de Santa Catarina.
```

**Comment by marcelolx** [comment]
Reunir pessoas com interesse e que já trabalham na área de tecnologia, que se sentem motivadas a compartilhar informações e técnicas de forma livre, através de projetos, posts e outras maneiras de forma a agregar e compartilhar conhecimento. 

Sugestion.

**Comment by johnidm** [comment]
Thanks @marcelolx

**Comment by jrmessias** [comment]
:+1:  Feito
