### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by jrmessias** [OESTIDigital/OESTIDigital.github.io#7]
Então, galera, para a galera começar a contribuir vai ter que fazer fork do deste repositório, alguém ai não sabe como o jekyll funciona? Que tal fazermos um post sobre o funcionamento do jekyll para então a galera poder contribuir com o blog?

**Comment by felippepuhle** [comment]
Acho uma boa. o @johnidm comentou comigo essa semana que estava preparando algo também.

**Comment by marcelolx** [comment]
Acho legal a ideia, aí quem estiver disposto a contribuir vai ter uma noção como funciona.

**Comment by johnidm** [comment]
Show, a ideia do post é legal, podemos agregar mais conteúdo como por exemplo geradores de sites estáticos.

Alguém ficou com a tarefa de gerenciar esse projeto no Trello?

**Comment by jrmessias** [comment]
Bacana @johnidm podemos adicionar outros mais, tenho alguns em mente.

Criei um pull request com o post sobre o Jekyll já que é o que utilizamos aqui no GitHub, assim a galera pode aprender e começar a contribuir.

**Comment by marcelolx** [comment]
@johnidm até o momento não, pelo menos ninguém se manifestou.
